# .travis.yml
language: node_js

node_js:
  - "lts/*"

os: windows

branches:
  only:
    - master

install:
  - npm install

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - npm run-script dist

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: build/IP.exe
  skip_cleanup: true

notifications:
  webhooks: https://outlook.office.com/webhook/9886f12b-180c-415a-a77d-91030ab09b8a@3cc63785-b8a2-41d1-bc44-7d8a8ffa3d6e/TravisCI/b27f0622ab454699ab5074ec6a91e4d9/81ecbf21-08c2-46d6-a47e-61844c772c05
