name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          cache: 'npm'

      - name: Use Node.js
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install Python dependencies
        run: pip install -r src/backend/requirements.txt

      - name: Update npm
        run: npm install --global npm@latest

      - name: Patch node-gyp to support Visual Studio 2019
        shell: powershell
        run: |
          npm install --global node-gyp@latest
          npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}

      - name: Install Global Dependencies
        run: npm install yarn -g

      - name: Install Dependencies & Build Native Files
        run: yarn install

      - name: Build & Deploy
        run: yarn run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
